explain:
	@echo "This is make practice"
	@echo "make build to build target"
	@echo "make exec to run"
	@echo "make clean to clean"

build:
	gcc main.c -o main

exec:
	./main

clean:
	rm main